name: Deployment

on:
  release:
    types: [created]

jobs:
  build-and-deploy:
    name: Build and Deploy

    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Dependencies installation
        run: |
          npm install
      - name: App build
        run: |
          npm run build:prod
      - name: Deployment
        run: |
          npm run deploy -- --repo=https://github.com/${{ env.GITHUB_REPOSITORY }}.git --name="${{ secrets.NAME }}" --email=${{ secrets.EMAIL }} --no-silent
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}