name: Deployment

on:
  release:
    types: [created]

jobs:
  build-and-deploy:
    name: Build and Deploy

    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Build
        run: |
          npm install
          npm run build --prod